from enum import StrEnum


class Field(StrEnum):
    PROBLEM_FILENAME = "PROBLEM_FILENAME"
    PROBLEM = "PROBLEM"
    PROPOSED_SOLUTION = "PROPOSED_SOLUTION"
    CRITICAL_FEEDBACK = "CRITICAL_FEEDBACK"
